# Generated by Django 3.2.5 on 2022-07-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolling_work', '0002_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
